apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rayservice-vllm
spec:
  serveConfigV2:  |
    applications:
      - name: llm_app
        import_path: serve_vllm:app
        route_prefix: /
  rayClusterConfig:
    rayVersion: '2.44.0'
    enableInTreeAutoscaling: true
    headGroupSpec:
      rayStartParams:
        num-cpus: "0"
      template:
        spec:
          nodeSelector:
            role: head
          containers:
            - name: ray-head
              image: 722323574575.dkr.ecr.us-east-1.amazonaws.com/multinode-llm-serving/ray-qwen-vllm:latest
              resources:
                limits:
                  cpu: "1"
                  memory: "2Gi"
                requests:
                  cpu: "500m"
                  memory: "2Gi"
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 1
        maxReplicas: 1
        groupName: gpu-group
        rayStartParams: { }
        template:
          spec:
            nodeSelector:
              role: gpu-worker
            containers:
              - name: ray-worker
                image: 722323574575.dkr.ecr.us-east-1.amazonaws.com/multinode-llm-serving/ray-qwen-vllm:latest
                resources:
                  limits:
                    cpu: "3"
                    memory: "12Gi"
                    nvidia.com/gpu: "1"
                  requests:
                    cpu: "2"
                    memory: "8Gi"
                    nvidia.com/gpu: "1"